In [ ]:
# import json
# import requests
# from bs4 import BeautifulSoup

# r = requests.get("https://www.worldbank.org/en/topic")
# soup = BeautifulSoup(r.content)

# topic_list = {}
# all_topics = []

# for topic in soup.find_all(attrs={"class": "topic-card"}):
#     topic_name = topic.find("img").attrs["title"].strip()
#     topic_list[topic_name] = [i.text.strip() for i in topic.find_all(attrs={"class": "topic-list-item"})]

#     all_topics.append(topic_name)
#     all_topics.extend(topic_list[topic_name])


# json.dumps(all_topics)


# # ["Agriculture and Food", "Food Security Update", "Climate-Smart Agriculture", "Livestock and Sustainability", "One Health", "Food System Jobs", "Agribusiness and Value Chains", "Climate Change", "Climate-Smart Agriculture", "Disaster Risk Management", "Competitiveness", "Competition Policy", "Investment Climate", "Innovation and Entrepreneurship", "Debt", "Debt Relief", "Digital Development", "Disaster Risk Management", "Education", "Early Childhood Development", "Education and Technology", "Girls' Education", "Higher Education", "Skills Development", "Teachers", "Energy", "Environment", "Biodiversity", "Marine Plastic Pollution", "Natural Capital", "Oceans, Fisheries, and Coastal Economies", "Pollution", "Forests and Landscapes", "Extractive Industries", "Mining Investment and Governance Review", "Gas Flaring Reduction", "Financial Inclusion", "Payment Systems", "Credit Infrastructure", "Small and Medium Enterprises Finance", "Financial Sector", "Financial Stability", "Financial Integrity", "Long-Term Finance", "Fragility, Conflict, and Violence", "Gender", "Governance", "Procurement for Development", "Health", "Infectious diseases and Vaccines", "Nutrition", "COVID-19 Hub", "Pandemic Preparedness and COVID-19", "Universal Health Coverage", "Global Financing Facility for Women, Children and Adolescents", "Inequality and Shared Prosperity", "Infrastructure", "Jobs & Development", "Labor Markets", "Skills Development", "Social Protection", "Macroeconomics", "Taxes and Government Revenue", "Migration", "Nutrition", "Poverty", "Inequality and Shared Prosperity", "Measuring Poverty", "Regional Integration", "Social Sustainability and Inclusion", "Community-Driven Development", "Disability Inclusion", "Indigenous Peoples", "Sexual Orientation and Gender Identity", "Social Inclusion", "Sustainable Communities", "Social Protection", "Jobs and Development", "Pensions", "Safety Nets and Cash Transfers", "Skills Development", "Sustainable Infrastructure Finance", "Trade", "Trade Facilitation and Logistics", "Global Value Chains", "Transport", "Urban Development", "Disaster Risk Management", "Inclusive Cities", "Land", "Water", "Sanitation", "Water in Agriculture", "Water Resources Management", "Water Supply"]

'["Agriculture and Food", "Food Security Update", "Climate-Smart Agriculture", "Livestock and Sustainability", "One Health", "Food System Jobs", "Agribusiness and Value Chains", "Climate Change", "Climate-Smart Agriculture", "Disaster Risk Management", "Competitiveness", "Competition Policy", "Investment Climate", "Innovation and Entrepreneurship", "Debt", "Debt Relief", "Digital Development", "Disaster Risk Management", "Education", "Early Childhood Development", "Education and Technology", "Girls\' Education", "Higher Education", "Skills Development", "Teachers", "Energy", "Environment", "Biodiversity", "Marine Plastic Pollution", "Natural Capital", "Oceans, Fisheries, and Coastal Economies", "Pollution", "Forests and Landscapes", "Extractive Industries", "Mining Investment and Governance Review", "Gas Flaring Reduction", "Financial Inclusion", "Payment Systems", "Credit Infrastructure", "Small and Medium Enterprises Finance", "Financial Sector", "Financial Stability", "Financial Integrity", "Long-Term Finance", "Fragility, Conflict, and Violence", "Gender", "Governance", "Procurement for Development", "Health", "Infectious diseases and Vaccines", "Nutrition", "COVID-19 Hub", "Pandemic Preparedness and COVID-19", "Universal Health Coverage", "Global Financing Facility for Women, Children and Adolescents", "Inequality and Shared Prosperity", "Infrastructure", "Jobs & Development", "Labor Markets", "Skills Development", "Social Protection", "Macroeconomics", "Taxes and Government Revenue", "Migration", "Nutrition", "Poverty", "Inequality and Shared Prosperity", "Measuring Poverty", "Regional Integration", "Social Sustainability and Inclusion", "Community-Driven Development", "Disability Inclusion", "Indigenous Peoples", "Sexual Orientation and Gender Identity", "Social Inclusion", "Sustainable Communities", "Social Protection", "Jobs and Development", "Pensions", "Safety Nets and Cash Transfers", "Skills Development", "Sustainable Infrastructure Finance", "Trade", "Trade Facilitation and Logistics", "Global Value Chains", "Transport", "Urban Development", "Disaster Risk Management", "Inclusive Cities", "Land", "Water", "Sanitation", "Water in Agriculture", "Water Resources Management", "Water Supply"]'

In [ ]:
import json
import requests
from bs4 import BeautifulSoup


h = '''Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Host: www.bestbuy.com
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"'''

headers = {i.split(": ")[0]: ": ".join(i.split(": ")[1:]) for i in h.split("\n")}

In [ ]:
lp = requests.get("https://www.bestbuy.com/site/nvidia-geforce-rtx-4090-24gb-gddr6x-graphics-card-titanium-black/6521430.p?skuId=6521430", headers=headers)
# lp = requests.get("https://www.bestbuy.com/site/asus-nvidia-geforce-rtx-4090-overclock-24gb-gddr6x-pci-express-4-0-strix-graphics-card-black/6524435.p?skuId=6524435", headers=headers)

b"Sold Out" in lp.content

In [ ]:
wb_topics = {
  "all_topics": [
    "Agriculture and Food",
    "Food Security Update",
    "Climate-Smart Agriculture",
    "Livestock and Sustainability",
    "One Health",
    "Food System Jobs",
    "Agribusiness and Value Chains",
    "Climate Change",
    "Climate-Smart Agriculture",
    "Disaster Risk Management",
    "Competitiveness",
    "Competition Policy",
    "Investment Climate",
    "Innovation and Entrepreneurship",
    "Debt",
    "Debt Relief",
    "Digital Development",
    "Disaster Risk Management",
    "Education",
    "Early Childhood Development",
    "Education and Technology",
    "Girls' Education",
    "Higher Education",
    "Skills Development",
    "Teachers",
    "Energy",
    "Environment",
    "Biodiversity",
    "Marine Plastic Pollution",
    "Natural Capital",
    "Oceans, Fisheries, and Coastal Economies",
    "Pollution",
    "Forests and Landscapes",
    "Extractive Industries",
    "Mining Investment and Governance Review",
    "Gas Flaring Reduction",
    "Financial Inclusion",
    "Payment Systems",
    "Credit Infrastructure",
    "Small and Medium Enterprises Finance",
    "Financial Sector",
    "Financial Stability",
    "Financial Integrity",
    "Long-Term Finance",
    "Fragility, Conflict, and Violence",
    "Gender",
    "Governance",
    "Procurement for Development",
    "Health",
    "Infectious diseases and Vaccines",
    "Nutrition",
    "COVID-19 Hub",
    "Pandemic Preparedness and COVID-19",
    "Universal Health Coverage",
    "Global Financing Facility for Women, Children and Adolescents",
    "Inequality and Shared Prosperity",
    "Infrastructure",
    "Jobs & Development",
    "Labor Markets",
    "Skills Development",
    "Social Protection",
    "Macroeconomics",
    "Taxes and Government Revenue",
    "Migration",
    "Nutrition",
    "Poverty",
    "Inequality and Shared Prosperity",
    "Measuring Poverty",
    "Regional Integration",
    "Social Sustainability and Inclusion",
    "Community-Driven Development",
    "Disability Inclusion",
    "Indigenous Peoples",
    "Sexual Orientation and Gender Identity",
    "Social Inclusion",
    "Sustainable Communities",
    "Social Protection",
    "Jobs and Development",
    "Pensions",
    "Safety Nets and Cash Transfers",
    "Skills Development",
    "Sustainable Infrastructure Finance",
    "Trade",
    "Trade Facilitation and Logistics",
    "Global Value Chains",
    "Transport",
    "Urban Development",
    "Disaster Risk Management",
    "Inclusive Cities",
    "Land",
    "Water",
    "Sanitation",
    "Water in Agriculture",
    "Water Resources Management",
    "Water Supply"
  ],
  "topic_list": {
    "Agriculture and Food": [
      "Food Security Update",
      "Climate-Smart Agriculture",
      "Livestock and Sustainability",
      "One Health",
      "Food System Jobs",
      "Agribusiness and Value Chains"
    ],
    "Climate Change": [
      "Climate-Smart Agriculture",
      "Disaster Risk Management"
    ],
    "Competitiveness": [
      "Competition Policy",
      "Investment Climate",
      "Innovation and Entrepreneurship"
    ],
    "Debt": [
      "Debt Relief"
    ],
    "Digital Development": [],
    "Disaster Risk Management": [],
    "Education": [
      "Early Childhood Development",
      "Education and Technology",
      "Girls' Education",
      "Higher Education",
      "Skills Development",
      "Teachers"
    ],
    "Energy": [],
    "Environment": [
      "Biodiversity",
      "Marine Plastic Pollution",
      "Natural Capital",
      "Oceans, Fisheries, and Coastal Economies",
      "Pollution",
      "Forests and Landscapes"
    ],
    "Extractive Industries": [
      "Mining Investment and Governance Review",
      "Gas Flaring Reduction"
    ],
    "Financial Inclusion": [
      "Payment Systems",
      "Credit Infrastructure",
      "Small and Medium Enterprises Finance"
    ],
    "Financial Sector": [
      "Financial Stability",
      "Financial Integrity",
      "Long-Term Finance"
    ],
    "Fragility, Conflict, and Violence": [],
    "Gender": [],
    "Governance": [
      "Procurement for Development"
    ],
    "Health": [
      "Infectious diseases and Vaccines",
      "Nutrition",
      "COVID-19 Hub",
      "Pandemic Preparedness and COVID-19",
      "Universal Health Coverage",
      "Global Financing Facility for Women, Children and Adolescents"
    ],
    "Inequality and Shared Prosperity": [],
    "Infrastructure": [],
    "Jobs & Development": [
      "Labor Markets",
      "Skills Development",
      "Social Protection"
    ],
    "Macroeconomics": [
      "Taxes and Government Revenue"
    ],
    "Migration": [],
    "Nutrition": [],
    "Poverty": [
      "Inequality and Shared Prosperity",
      "Measuring Poverty"
    ],
    "Regional Integration": [],
    "Social Sustainability and Inclusion": [
      "Community-Driven Development",
      "Disability Inclusion",
      "Indigenous Peoples",
      "Sexual Orientation and Gender Identity",
      "Social Inclusion",
      "Sustainable Communities"
    ],
    "Social Protection": [
      "Jobs and Development",
      "Pensions",
      "Safety Nets and Cash Transfers",
      "Skills Development"
    ],
    "Sustainable Infrastructure Finance": [],
    "Trade": [
      "Trade Facilitation and Logistics",
      "Global Value Chains"
    ],
    "Transport": [],
    "Urban Development": [
      "Disaster Risk Management",
      "Inclusive Cities",
      "Land"
    ],
    "Water": [
      "Sanitation",
      "Water in Agriculture",
      "Water Resources Management",
      "Water Supply"
    ]
  }
}

In [4]:
!pip install datasets evaluate transformers[torch] &> /dev/null
!pip install accelerate -U

Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (0.34.2)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (24.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.4.0+cu121)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.24.6)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.4.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (3.16.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2024.6.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (1.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)

In [5]:
!pip install -U huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.10/dist-packages (0.24.6)
Collecting huggingface_hub
  Downloading huggingface_hub-0.24.7-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (3.16.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2024.8.30)
Downloading huggingface_hub-0.24.7-py3-none-any.whl (417 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.5/417.5 kB 14.7 MB/s eta 0:00:00
Installing collected packages: huggingface_hub
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.24.6
    Uninstalling huggingface-hub-0.24.6:
      Successfully uninstalled huggingface-hub-0.24.6
Successfully installed huggingface_hub-0.24.7

In [4]:
from transformers import AutoConfig, AutoModel, AutoTokenizer
import transformers
import datasets


model_path = 'microsoft/deberta-v3-small'
tokenizer = AutoTokenizer.from_pretrained(model_path)

data = datasets.load_dataset("avsolatorio/doc-topics-synthetic_data", data_dir="processed", split="train", revision="e6d841658894fc096d8e0df3fb0567c201250bfc")

classes = list(set(wb_topics["all_topics"]))
class2id = {class_:id for id, class_ in enumerate(classes)}
id2class = {id:class_ for class_, id in class2id.items()}

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py:551: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

In [5]:
def preprocess_function(example):
    try:
        example["valid"] = True

        text = example["sentence"] or ""

        all_labels = example["topics"] or []

        if text == "" or len(all_labels) == 0:
            example["valid"] = False

        labels = [0. for i in range(len(classes))]
        for label in all_labels:
            if label not in class2id:
                example["valid"] = False
                continue

            label_id = class2id[label]
            labels[label_id] = 1.

        if not any(labels):
            example["valid"] = False

        example = tokenizer(text, truncation=True)
        example['labels'] = labels
        return example
    except Exception as e:
        print(example)
        raise e

dataset = data
print(len(dataset))

tokenized_dataset = dataset.map(preprocess_function)
tokenized_dataset = tokenized_dataset.filter(lambda x: x["valid"])

tokenized_dataset

41416

Map:   0%|          | 0/41416 [00:00<?, ? examples/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Filter:   0%|          | 0/41416 [00:00<?, ? examples/s]

Dataset({
    features: ['sentence', 'topics', 'model_name', 'valid', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 40553
})

In [6]:
from transformers import DataCollatorWithPadding


data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [7]:
import evaluate
import numpy as np


clf_metrics = evaluate.combine(["accuracy", "f1", "precision", "recall"])


def sigmoid(x):
    return 1/(1 + np.exp(-x))


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = sigmoid(predictions)
    predictions = (predictions > 0.5).astype(int).reshape(-1)

    return clf_metrics.compute(predictions=predictions, references=labels.astype(int).reshape(-1))

In [8]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(
        model_path,
        num_labels=len(classes),
        id2label=id2class,
        label2id=class2id,
        problem_type="multi_label_classification"
    )

model = model_init()

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-small and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
# tokenized_dataset = tokenized_dataset.train_test_split(test_size=0.2, seed=42)
# tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'topics', 'model_name', 'valid', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 32442
    })
    test: Dataset({
        features: ['sentence', 'topics', 'model_name', 'valid', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 8111
    })
})

In [ ]:
# Split the data into 5 groups
# Train 5 separate models
# Use the 4 models to validate the LLM assigned topics as well as infer potentially missing topics.
# A label is valid if 3 out of 4 models agree on a topic for a given sample.
# Once all the data groups have been imputed, shuffle and repeat the process until convergence.

In [9]:
from datasets import Dataset

# Get the length of the dataset
dataset_length = len(tokenized_dataset)

# Calculate the size of each subset
subset_size = dataset_length // 5

# Split into 5 equally sized subdatasets
subdatasets = []
remaining_dataset = tokenized_dataset

for i in range(4):  # Split the first 4 subdatasets
    split_dataset = remaining_dataset.train_test_split(test_size=subset_size, seed=42)
    subdatasets.append(split_dataset['test'])
    remaining_dataset = split_dataset['train']

# Append the remaining part as the fifth subdataset
subdatasets.append(remaining_dataset)

# subdatasets is now a list of 5 subdatasets
len(subdatasets)

5

In [10]:
subdatasets[0]

Dataset({
    features: ['sentence', 'topics', 'model_name', 'valid', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 8110
})

In [11]:
subdatasets[-1]

Dataset({
    features: ['sentence', 'topics', 'model_name', 'valid', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 8113
})

In [12]:
len(id2class)

87

In [ ]:
N = len(subdatasets)
# run_num = 1
# split = 0

for eval_split in range(N):
    for train_split in range(N):
        if eval_split == train_split:
            continue

        model_dirname = f"doc-topic-model_eval-{eval_split:02}_train-{train_split:02}"

        training_args = TrainingArguments(
            output_dir=f"{model_dirname}",
            learning_rate=2e-5,
            per_device_train_batch_size=4,
            per_device_eval_batch_size=16,
            num_train_epochs=10,
            weight_decay=0.01,
            evaluation_strategy="steps",
            eval_steps=1000,
            save_steps=1000,
            save_strategy="steps",
            load_best_model_at_end=True,
            save_total_limit=4,
            push_to_hub=True,
            hub_strategy="checkpoint",
            # hub_model_id="avsolatorio/doc-topic-model",
            hub_model_id=f"avsolatorio/{model_dirname}",
            hub_private_repo=True,
            seed=42,
        )

        trainer = Trainer(
            model_init=model_init,
            #    model=model,
            args=training_args,
            #    train_dataset=tokenized_dataset["train"],
            #    eval_dataset=tokenized_dataset["test"],
            train_dataset=subdatasets[train_split],
            eval_dataset=subdatasets[eval_split],
            tokenizer=tokenizer,
            data_collator=data_collator,
            compute_metrics=compute_metrics,
        )

        trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-small and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-small and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
run_num = 1
split = 1
run_name = f"run-{run_num:02}-split-{split:02}"
model_dirname = "doc-topic-model-ensemble"

training_args = TrainingArguments(
   output_dir=f"{model_dirname}/{run_name}",
   learning_rate=2e-5,
   per_device_train_batch_size=4,
   per_device_eval_batch_size=16,
   num_train_epochs=10,
   weight_decay=0.01,
   evaluation_strategy="steps",
   eval_steps=1000,
   save_steps=1000,
   save_strategy="steps",
   load_best_model_at_end=True,
   save_total_limit=4,
   push_to_hub=True,
   hub_strategy="checkpoint",
   # hub_model_id="avsolatorio/doc-topic-model",
   hub_model_id=f"avsolatorio/{model_dirname}/{run_name}",
   hub_private_repo=True,
   seed=42,
)

trainer = Trainer(
    model_init=model_init,
#    model=model,
   args=training_args,
   train_dataset=tokenized_dataset["train"],
   eval_dataset=tokenized_dataset["test"],
   tokenizer=tokenizer,
   data_collator=data_collator,
   compute_metrics=compute_metrics,
)

trainer.train()

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
# !rm -rf /content/_doc_topic_model

In [ ]:
from transformers import pipeline
from transformers.pipelines.pt_utils import KeyDataset
from tqdm.auto import tqdm

classifier = pipeline("text-classification", model=model, tokenizer=tokenizer, top_k=None)

In [ ]:
inp = "Special emphasis is given to the Living Standard Measurement Study (LSMS) household surveys, but also included in the review of data collection at the individual level are surv eys conducted by the In ternational Food Policy Research Institute (IFPRI) and the Internationa l Center for Research on Women (ICRW)."
inp = "Using a long panel of household survey data from Bangladesh, the paper finds that some 26 percent of microcredit borrowers are over-indebted on this This paper is a product of the Agriculture and Rural Development Team, Development Research Group."
inp = "Yet he was failing: failing to create a work environment for his staff in which they felt engaged, mentored, and safe."
classifier(inp)

[[{'label': 'Labor Markets', 'score': 0.637760579586029},
  {'label': 'Skills Development', 'score': 0.4212106168270111},
  {'label': 'Jobs & Development', 'score': 0.26052990555763245},
  {'label': 'Jobs and Development', 'score': 0.16517691314220428},
  {'label': 'Gender', 'score': 0.05356895551085472},
  {'label': 'Social Sustainability and Inclusion',
   'score': 0.031715527176856995},
  {'label': 'Social Inclusion', 'score': 0.01956660859286785},
  {'label': 'Food System Jobs', 'score': 0.009972138330340385},
  {'label': 'Social Protection', 'score': 0.008768811821937561},
  {'label': 'Sexual Orientation and Gender Identity',
   'score': 0.008624855428934097},
  {'label': 'Education', 'score': 0.008321383967995644},
  {'label': 'Teachers', 'score': 0.007017497904598713},
  {'label': 'Governance', 'score': 0.00614815391600132},
  {'label': 'Higher Education', 'score': 0.005934218876063824},
  {'label': 'Competition Policy', 'score': 0.004070964641869068},
  {'label': 'Competitiveness', 'score': 0.0032449038699269295},
  {'label': 'Migration', 'score': 0.00260388501919806},
  {'label': 'Disability Inclusion', 'score': 0.0017242964822798967},
  {'label': 'Inequality and Shared Prosperity',
   'score': 0.0015715154586359859},
  {'label': 'Poverty', 'score': 0.001527370885014534},
  {'label': 'Investment Climate', 'score': 0.001381648937240243},
  {'label': 'Education and Technology', 'score': 0.0013053517322987318},
  {'label': 'Global Value Chains', 'score': 0.0010298460256308317},
  {'label': 'Macroeconomics', 'score': 0.0009623473160900176},
  {'label': 'Inclusive Cities', 'score': 0.0008273936691693962},
  {'label': 'Pensions', 'score': 0.0007309747743420303},
  {'label': 'Measuring Poverty', 'score': 0.0005626120255328715},
  {'label': 'Long-Term Finance', 'score': 0.0005063576390966773},
  {'label': 'Innovation and Entrepreneurship', 'score': 0.0004969389410689473},
  {'label': 'Universal Health Coverage', 'score': 0.00042099019628949463},
  {'label': 'Financial Inclusion', 'score': 0.0004083631793037057},
  {'label': 'Sustainable Communities', 'score': 0.0004016309103462845},
  {'label': 'Digital Development', 'score': 0.0003820556157734245},
  {'label': 'Agriculture and Food', 'score': 0.00038049451541155577},
  {'label': 'Procurement for Development', 'score': 0.00036056202952750027},
  {'label': 'Health', 'score': 0.00033897263347171247},
  {'label': 'Small and Medium Enterprises Finance',
   'score': 0.0003292889450676739},
  {'label': 'Global Financing Facility for Women, Children and Adolescents',
   'score': 0.00031917134765535593},
  {'label': 'Financial Stability', 'score': 0.00028693038620986044},
  {'label': "Girls' Education", 'score': 0.0002839602530002594},
  {'label': 'One Health', 'score': 0.0002801527443807572},
  {'label': 'Community-Driven Development', 'score': 0.0002776870969682932},
  {'label': 'Urban Development', 'score': 0.00023709236120339483},
  {'label': 'Agribusiness and Value Chains', 'score': 0.0002258819149574265},
  {'label': 'Biodiversity', 'score': 0.00021137864678166807},
  {'label': 'Safety Nets and Cash Transfers', 'score': 0.00020178321574348956},
  {'label': 'Trade', 'score': 0.00018479724531061947},
  {'label': 'Financial Sector', 'score': 0.00016828988736961037},
  {'label': 'Infrastructure', 'score': 0.0001656403037486598},
  {'label': 'Environment', 'score': 0.000163969089044258},
  {'label': 'Land', 'score': 0.00015347969019785523},
  {'label': 'Extractive Industries', 'score': 0.00014193388051353395},
  {'label': 'Fragility, Conflict, and Violence',
   'score': 0.00012050120858475566},
  {'label': 'Transport', 'score': 0.00010064776142826304},
  {'label': 'Mining Investment and Governance Review',
   'score': 9.39184901653789e-05},
  {'label': 'COVID-19 Hub', 'score': 8.626982889836654e-05},
  {'label': 'Regional Integration', 'score': 7.822881161700934e-05},
  {'label': 'Taxes and Government Revenue', 'score': 7.702474249526858e-05},
  {'label': 'Climate Change', 'score': 7.66348239267245e-05},
  {'label': 'Livestock and Sustainability', 'score': 7.564340194221586e-05},
  {'label': 'Financial Integrity', 'score': 7.352203829213977e-05},
  {'label': 'Water', 'score': 7.277309487108141e-05},
  {'label': 'Food Security Update', 'score': 6.784157449146733e-05},
  {'label': 'Indigenous Peoples', 'score': 6.300451786955819e-05},
  {'label': 'Pandemic Preparedness and COVID-19',
   'score': 6.195027526700869e-05},
  {'label': 'Energy', 'score': 5.6186519941547886e-05},
  {'label': 'Trade Facilitation and Logistics',
   'score': 5.042957855039276e-05},
  {'label': 'Infectious diseases and Vaccines',
   'score': 4.2088617192348465e-05},
  {'label': 'Credit Infrastructure', 'score': 3.935331551474519e-05},
  {'label': 'Payment Systems', 'score': 3.912751708412543e-05},
  {'label': 'Pollution', 'score': 3.697644569911063e-05},
  {'label': 'Sustainable Infrastructure Finance',
   'score': 3.225819091312587e-05},
  {'label': 'Early Childhood Development', 'score': 2.8259613827685826e-05},
  {'label': 'Marine Plastic Pollution', 'score': 2.764227428997401e-05},
  {'label': 'Oceans, Fisheries, and Coastal Economies',
   'score': 2.749992381723132e-05},
  {'label': 'Natural Capital', 'score': 2.6211304430034943e-05},
  {'label': 'Water Supply', 'score': 2.501900053175632e-05},
  {'label': 'Water in Agriculture', 'score': 2.424029662506655e-05},
  {'label': 'Debt', 'score': 2.2648346202913672e-05},
  {'label': 'Forests and Landscapes', 'score': 1.9332170268171467e-05},
  {'label': 'Water Resources Management', 'score': 1.8043179807136767e-05},
  {'label': 'Climate-Smart Agriculture', 'score': 9.250382390746381e-06},
  {'label': 'Sanitation', 'score': 8.180314580386039e-06},
  {'label': 'Nutrition', 'score': 7.232415555336047e-06},
  {'label': 'Disaster Risk Management', 'score': 2.0277734620322008e-06},
  {'label': 'Gas Flaring Reduction', 'score': 1.5170204505920992e-06},
  {'label': 'Debt Relief', 'score': 1.3761916761723114e-06}]]

In [ ]:
topics = [k for t in data["topics"] for k in (t or []) if k in class2id]

In [ ]:
from collections import Counter

topic_count = Counter(topics)
len(topic_count)

87

In [ ]:
len(topic_count)

229

In [ ]:
topic_count.most_common()

[('Environment', 1105),
 ('Poverty', 933),
 ('Sustainable Communities', 897),
 ('Social Inclusion', 863),
 ('Governance', 851),
 ('Social Sustainability and Inclusion', 841),
 ('Climate Change', 829),
 ('Inclusive Cities', 802),
 ('Social Protection', 801),
 ('Inequality and Shared Prosperity', 800),
 ('Infrastructure', 796),
 ('Urban Development', 787),
 ('Education', 786),
 ('Sustainable Infrastructure Finance', 784),
 ('Energy', 777),
 ('Health', 774),
 ('Financial Sector', 770),
 ('Agriculture and Food', 766),
 ('Global Value Chains', 758),
 ('Financial Inclusion', 755),
 ('Innovation and Entrepreneurship', 754),
 ('Community-Driven Development', 749),
 ('Digital Development', 749),
 ('Natural Capital', 740),
 ('Trade', 734),
 ('Competitiveness', 730),
 ('Nutrition', 726),
 ('Forests and Landscapes', 726),
 ('Water', 725),
 ('Financial Stability', 718),
 ('Pollution', 718),
 ('Sanitation', 716),
 ('Water Resources Management', 715),
 ('Education and Technology', 712),
 ('Jobs & Development', 709),
 ('COVID-19 Hub', 701),
 ('Livestock and Sustainability', 701),
 ('Higher Education', 699),
 ('Financial Integrity', 694),
 ('Macroeconomics', 689),
 ('Food Security Update', 688),
 ('Agribusiness and Value Chains', 685),
 ('Gender', 681),
 ('Migration', 681),
 ('Climate-Smart Agriculture', 681),
 ('Disaster Risk Management', 674),
 ('Skills Development', 674),
 ('Payment Systems', 670),
 ('Labor Markets', 667),
 ('Universal Health Coverage', 664),
 ('Safety Nets and Cash Transfers', 661),
 ('Infectious diseases and Vaccines', 660),
 ('Measuring Poverty', 659),
 ('Debt', 658),
 ('Water Supply', 656),
 ('Small and Medium Enterprises Finance', 656),
 ('Regional Integration', 655),
 ('Biodiversity', 655),
 ("Girls' Education", 655),
 ('Investment Climate', 655),
 ('Jobs and Development', 654),
 ('One Health', 654),
 ('Early Childhood Development', 645),
 ('Pandemic Preparedness and COVID-19', 643),
 ('Indigenous Peoples', 643),
 ('Land', 636),
 ('Pensions', 630),
 ('Global Financing Facility for Women, Children and Adolescents', 627),
 ('Long-Term Finance', 619),
 ('Trade Facilitation and Logistics', 618),
 ('Competition Policy', 616),
 ('Procurement for Development', 615),
 ('Disability Inclusion', 614),
 ('Credit Infrastructure', 614),
 ('Fragility, Conflict, and Violence', 614),
 ('Taxes and Government Revenue', 610),
 ('Extractive Industries', 606),
 ('Transport', 603),
 ('Water in Agriculture', 598),
 ('Mining Investment and Governance Review', 590),
 ('Debt Relief', 589),
 ('Marine Plastic Pollution', 579),
 ('Oceans, Fisheries, and Coastal Economies', 559),
 ('Teachers', 557),
 ('Sexual Orientation and Gender Identity', 550),
 ('Gas Flaring Reduction', 537),
 ('Food System Jobs', 516)]

In [ ]:
topic_count.most_common()

[('Environment', 1105),
 ('Poverty', 933),
 ('Sustainable Communities', 897),
 ('Social Inclusion', 863),
 ('Governance', 851),
 ('Social Sustainability and Inclusion', 841),
 ('Climate Change', 829),
 ('Inclusive Cities', 802),
 ('Social Protection', 801),
 ('Inequality and Shared Prosperity', 800),
 ('Infrastructure', 796),
 ('Urban Development', 787),
 ('Education', 786),
 ('Sustainable Infrastructure Finance', 784),
 ('Energy', 777),
 ('Health', 774),
 ('Financial Sector', 770),
 ('Agriculture and Food', 766),
 ('Global Value Chains', 758),
 ('Financial Inclusion', 755),
 ('Innovation and Entrepreneurship', 754),
 ('Community-Driven Development', 749),
 ('Digital Development', 749),
 ('Natural Capital', 740),
 ('Trade', 734),
 ('Competitiveness', 730),
 ('Nutrition', 726),
 ('Forests and Landscapes', 726),
 ('Water', 725),
 ('Financial Stability', 718),
 ('Pollution', 718),
 ('Sanitation', 716),
 ('Water Resources Management', 715),
 ('Education and Technology', 712),
 ('Jobs & Development', 709),
 ('COVID-19 Hub', 701),
 ('Livestock and Sustainability', 701),
 ('Higher Education', 699),
 ('Financial Integrity', 694),
 ('Macroeconomics', 689),
 ('Food Security Update', 688),
 ('Agribusiness and Value Chains', 685),
 ('Gender', 681),
 ('Migration', 681),
 ('Climate-Smart Agriculture', 681),
 ('Disaster Risk Management', 674),
 ('Skills Development', 674),
 ('Payment Systems', 670),
 ('Labor Markets', 667),
 ('Universal Health Coverage', 664),
 ('Safety Nets and Cash Transfers', 661),
 ('Infectious diseases and Vaccines', 660),
 ('Measuring Poverty', 659),
 ('Debt', 658),
 ('Water Supply', 656),
 ('Small and Medium Enterprises Finance', 656),
 ('Regional Integration', 655),
 ('Biodiversity', 655),
 ("Girls' Education", 655),
 ('Investment Climate', 655),
 ('Jobs and Development', 654),
 ('One Health', 654),
 ('Early Childhood Development', 645),
 ('Pandemic Preparedness and COVID-19', 643),
 ('Indigenous Peoples', 643),
 ('Land', 636),
 ('Pensions', 630),
 ('Global Financing Facility for Women, Children and Adolescents', 627),
 ('Long-Term Finance', 619),
 ('Trade Facilitation and Logistics', 618),
 ('Competition Policy', 616),
 ('Procurement for Development', 615),
 ('Disability Inclusion', 614),
 ('Credit Infrastructure', 614),
 ('Fragility, Conflict, and Violence', 614),
 ('Taxes and Government Revenue', 610),
 ('Extractive Industries', 606),
 ('Transport', 603),
 ('Water in Agriculture', 598),
 ('Mining Investment and Governance Review', 590),
 ('Debt Relief', 589),
 ('Marine Plastic Pollution', 579),
 ('Oceans, Fisheries, and Coastal Economies', 559),
 ('Teachers', 557),
 ('Sexual Orientation and Gender Identity', 550),
 ('Gas Flaring Reduction', 537),
 ('Food System Jobs', 516),
 ('Oceans', 69),
 ('Food System', 57),
 ('Environmental Sustainability', 53),
 ('Fisheries', 51),
 ('Sustainability', 49),
 ('Coastal Economies', 46),
 ('Jobs', 43),
 ('Fragility', 38),
 ('Environmental Protection', 35),
 ('Conflict', 32),
 ('Technology', 30),
 ('Economic Development', 25),
 ('Governance Review', 24),
 ('Mining', 22),
 ('Economy', 20),
 ('Violence', 17),
 ('Public Health', 17),
 ('Economic Growth', 15),
 ('Environmental Conservation', 14),
 ('Investment', 13),
 ('Economic Policy', 11),
 ('Sustainable Development', 10),
 ('Economic Stability', 9),
 ('Healthcare', 8),
 ('Environmental Policy', 8),
 ('Environmental Impact', 8),
 ('Government Revenue', 6),
 ('Human Rights', 6),
 ('Agriculture', 6),
 ('Innovation', 6),
 ('Infectious diseases', 6),
 ('Poverty Reduction', 5),
 ('Fisheries and Coastal Economies', 5),
 ('Inequality', 5),
 ('Food Security', 5),
 ('Review', 4),
 ('Social Sustainability', 4),
 ('Shared Prosperity', 4),
 ('Mining Investment', 4),
 ('Environmental', 4),
 ('Economic Sustainability', 4),
 ('and Violence', 4),
 ('Digital Transformation', 4),
 ('Vaccines', 4),
 ('Development', 3),
 ('Conflict, and Violence', 3),
 ('Taxes', 3),
 ('Safety Nets', 3),
 ('Small And Medium Enterprises Finance', 3),
 ('Sustainable Practices', 3),
 ('Global Pandemics', 3),
 ('Sustainable Agriculture', 3),
 ('Globalization', 3),
 ('Gender Equality', 3),
 ('Economics', 3),
 ('Land Rights', 3),
 ('Conflict and Violence', 3),
 ('Procurement', 2),
 ('And Violence', 2),
 ('Child Development', 2),
 ('Public Services', 2),
 ('Aging Population', 2),
 ('Global Health Initiatives', 2),
 ('Global Health', 2),
 ('Climate Change Adaptation', 2),
 ('Inclusivity', 2),
 ('Digital Innovation', 2),
 ('Economies', 2),
 ('Global Economy', 2),
 ('Empowerment', 2),
 ('Biodiversity Conservation', 2),
 ('Inclusion', 1),
 ('Govenance', 1),
 ('Labour', 1),
 ('Skil', 1),
 ('Minning Investment and Governance Review', 1),
 ('Climate-Small Agriculture', 1),
 ('Refugees', 1),
 ('Infectious diseases and Vacces', 1),
 ('Cash Transfers', 1),
 ('Taxed and Government Revenue', 1),
 ('Small and Medium Enterprises', 1),
 ('Public Policy', 1),
 ('Technical Innovation', 1),
 ('Economic Policies', 1),
 ('International Relations', 1),
 ('Public Spaces', 1),
 ('Digital Divide', 1),
 ('Technological Innovation', 1),
 ('Economic Planning', 1),
 ('Social Policy', 1),
 ('Social Welfare', 1),
 ('Workplace Diversity', 1),
 ('Humanitarian Aid', 1),
 ('Social Welfare Policies', 1),
 ('Nutrition and Food Security', 1),
 ('Digital Economy', 1),
 ('Peacebuilding', 1),
 ('Cultural Heritage Preservation', 1),
 ('Equity', 1),
 ('Fiscal Policy', 1),
 ('Economic Opportunities', 1),
 ('Cultural Heritage', 1),
 ('Educational and Technology', 1),
 ('Workplace Environment', 1),
 ('Educators', 1),
 ('Regulation', 1),
 ('Public-Private Partnerships', 1),
 ('Digital Literacy', 1),
 ('Conservation Efforts', 1),
 ('Cultural Preservation', 1),
 ('Sustainable Practice', 1),
 ('Agricultural Technology', 1),
 ('Health Security', 1),
 ('Socio-economic Indicators', 1),
 ('Social Justice', 1),
 ('Conservation', 1),
 ('Urban Planning', 1),
 ('Market Dynamics', 1),
 ('Global Challenges', 1),
 ('Green Technology', 1),
 ('Extraction Industries', 1),
 ('Corporate Social Responsibility', 1),
 ('Ethics', 1),
 ('Workplace Equality', 1),
 ('Global Finance', 1),
 ('Cyber Security', 1),
 ('Educational Strategies', 1),
 ('Global Development', 1),
 ('Ecosystem Services', 1),
 ('Public Health Campaigns', 1),
 ('Technology in Learning', 1),
 ('Community Rebuilding', 1),
 ('Economic Empowerment', 1),
 ('Transparency', 1),
 ('Infrastructure Development', 1),
 ('Health Equity', 1),
 ('Sustainable Energy', 1),
 ('Environmental Policies', 1),
 ('Healthcare Improvement', 1),
 ('Social Inequality', 1),
 ('Forest and Landscapes', 1)]